// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v3.20.3
// source: transactions.proto

package transactionprotogen

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Transactionmsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transactionid int32                  `protobuf:"varint,1,opt,name=transactionid,proto3" json:"transactionid,omitempty"`
	AccountId     int32                  `protobuf:"varint,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Amount        int32                  `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Type          string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transactionmsg) Reset() {
	*x = Transactionmsg{}
	mi := &file_transactions_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transactionmsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transactionmsg) ProtoMessage() {}

func (x *Transactionmsg) ProtoReflect() protoreflect.Message {
	mi := &file_transactions_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transactionmsg.ProtoReflect.Descriptor instead.
func (*Transactionmsg) Descriptor() ([]byte, []int) {
	return file_transactions_proto_rawDescGZIP(), []int{0}
}

func (x *Transactionmsg) GetTransactionid() int32 {
	if x != nil {
		return x.Transactionid
	}
	return 0
}

func (x *Transactionmsg) GetAccountId() int32 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *Transactionmsg) GetAmount() int32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Transactionmsg) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type Updatetransactionmsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transactionid int32                  `protobuf:"varint,1,opt,name=transactionid,proto3" json:"transactionid,omitempty"`
	Tokenstring   string                 `protobuf:"bytes,5,opt,name=tokenstring,proto3" json:"tokenstring,omitempty"`
	Amount        *int32                 `protobuf:"varint,2,opt,name=amount,proto3,oneof" json:"amount,omitempty"`
	Type          *string                `protobuf:"bytes,3,opt,name=type,proto3,oneof" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Updatetransactionmsg) Reset() {
	*x = Updatetransactionmsg{}
	mi := &file_transactions_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Updatetransactionmsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Updatetransactionmsg) ProtoMessage() {}

func (x *Updatetransactionmsg) ProtoReflect() protoreflect.Message {
	mi := &file_transactions_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Updatetransactionmsg.ProtoReflect.Descriptor instead.
func (*Updatetransactionmsg) Descriptor() ([]byte, []int) {
	return file_transactions_proto_rawDescGZIP(), []int{1}
}

func (x *Updatetransactionmsg) GetTransactionid() int32 {
	if x != nil {
		return x.Transactionid
	}
	return 0
}

func (x *Updatetransactionmsg) GetTokenstring() string {
	if x != nil {
		return x.Tokenstring
	}
	return ""
}

func (x *Updatetransactionmsg) GetAmount() int32 {
	if x != nil && x.Amount != nil {
		return *x.Amount
	}
	return 0
}

func (x *Updatetransactionmsg) GetType() string {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return ""
}

type Deletetransactionmsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transactionid int32                  `protobuf:"varint,1,opt,name=transactionid,proto3" json:"transactionid,omitempty"`
	Tokenstring   string                 `protobuf:"bytes,2,opt,name=tokenstring,proto3" json:"tokenstring,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Deletetransactionmsg) Reset() {
	*x = Deletetransactionmsg{}
	mi := &file_transactions_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Deletetransactionmsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Deletetransactionmsg) ProtoMessage() {}

func (x *Deletetransactionmsg) ProtoReflect() protoreflect.Message {
	mi := &file_transactions_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Deletetransactionmsg.ProtoReflect.Descriptor instead.
func (*Deletetransactionmsg) Descriptor() ([]byte, []int) {
	return file_transactions_proto_rawDescGZIP(), []int{2}
}

func (x *Deletetransactionmsg) GetTransactionid() int32 {
	if x != nil {
		return x.Transactionid
	}
	return 0
}

func (x *Deletetransactionmsg) GetTokenstring() string {
	if x != nil {
		return x.Tokenstring
	}
	return ""
}

type Transactionaddedmsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tokenstring   string                 `protobuf:"bytes,1,opt,name=tokenstring,proto3" json:"tokenstring,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transactionaddedmsg) Reset() {
	*x = Transactionaddedmsg{}
	mi := &file_transactions_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transactionaddedmsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transactionaddedmsg) ProtoMessage() {}

func (x *Transactionaddedmsg) ProtoReflect() protoreflect.Message {
	mi := &file_transactions_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transactionaddedmsg.ProtoReflect.Descriptor instead.
func (*Transactionaddedmsg) Descriptor() ([]byte, []int) {
	return file_transactions_proto_rawDescGZIP(), []int{3}
}

func (x *Transactionaddedmsg) GetTokenstring() string {
	if x != nil {
		return x.Tokenstring
	}
	return ""
}

func (x *Transactionaddedmsg) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type Transactionstatusmsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Status        int32                  `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transactionstatusmsg) Reset() {
	*x = Transactionstatusmsg{}
	mi := &file_transactions_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transactionstatusmsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transactionstatusmsg) ProtoMessage() {}

func (x *Transactionstatusmsg) ProtoReflect() protoreflect.Message {
	mi := &file_transactions_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transactionstatusmsg.ProtoReflect.Descriptor instead.
func (*Transactionstatusmsg) Descriptor() ([]byte, []int) {
	return file_transactions_proto_rawDescGZIP(), []int{4}
}

func (x *Transactionstatusmsg) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Transactionstatusmsg) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type Getsingletransactionmsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transactionid int32                  `protobuf:"varint,1,opt,name=transactionid,proto3" json:"transactionid,omitempty"`
	Tokenstring   string                 `protobuf:"bytes,2,opt,name=tokenstring,proto3" json:"tokenstring,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Getsingletransactionmsg) Reset() {
	*x = Getsingletransactionmsg{}
	mi := &file_transactions_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Getsingletransactionmsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Getsingletransactionmsg) ProtoMessage() {}

func (x *Getsingletransactionmsg) ProtoReflect() protoreflect.Message {
	mi := &file_transactions_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Getsingletransactionmsg.ProtoReflect.Descriptor instead.
func (*Getsingletransactionmsg) Descriptor() ([]byte, []int) {
	return file_transactions_proto_rawDescGZIP(), []int{5}
}

func (x *Getsingletransactionmsg) GetTransactionid() int32 {
	if x != nil {
		return x.Transactionid
	}
	return 0
}

func (x *Getsingletransactionmsg) GetTokenstring() string {
	if x != nil {
		return x.Tokenstring
	}
	return ""
}

type Getalltransactionsmsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Listtran      []*Transactionmsg      `protobuf:"bytes,1,rep,name=listtran,proto3" json:"listtran,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Getalltransactionsmsg) Reset() {
	*x = Getalltransactionsmsg{}
	mi := &file_transactions_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Getalltransactionsmsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Getalltransactionsmsg) ProtoMessage() {}

func (x *Getalltransactionsmsg) ProtoReflect() protoreflect.Message {
	mi := &file_transactions_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Getalltransactionsmsg.ProtoReflect.Descriptor instead.
func (*Getalltransactionsmsg) Descriptor() ([]byte, []int) {
	return file_transactions_proto_rawDescGZIP(), []int{6}
}

func (x *Getalltransactionsmsg) GetListtran() []*Transactionmsg {
	if x != nil {
		return x.Listtran
	}
	return nil
}

var File_transactions_proto protoreflect.FileDescriptor

const file_transactions_proto_rawDesc = "" +
	"\n" +
	"\x12transactions.proto\x12\x12accounttransaction\"\x81\x01\n" +
	"\x0eTransactionmsg\x12$\n" +
	"\rtransactionid\x18\x01 \x01(\x05R\rtransactionid\x12\x1d\n" +
	"\n" +
	"account_id\x18\x02 \x01(\x05R\taccountId\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x05R\x06amount\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\"\xa8\x01\n" +
	"\x14Updatetransactionmsg\x12$\n" +
	"\rtransactionid\x18\x01 \x01(\x05R\rtransactionid\x12 \n" +
	"\vtokenstring\x18\x05 \x01(\tR\vtokenstring\x12\x1b\n" +
	"\x06amount\x18\x02 \x01(\x05H\x00R\x06amount\x88\x01\x01\x12\x17\n" +
	"\x04type\x18\x03 \x01(\tH\x01R\x04type\x88\x01\x01B\t\n" +
	"\a_amountB\a\n" +
	"\x05_type\"^\n" +
	"\x14Deletetransactionmsg\x12$\n" +
	"\rtransactionid\x18\x01 \x01(\x05R\rtransactionid\x12 \n" +
	"\vtokenstring\x18\x02 \x01(\tR\vtokenstring\"Q\n" +
	"\x13transactionaddedmsg\x12 \n" +
	"\vtokenstring\x18\x01 \x01(\tR\vtokenstring\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"H\n" +
	"\x14transactionstatusmsg\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x16\n" +
	"\x06status\x18\x02 \x01(\x05R\x06status\"a\n" +
	"\x17getsingletransactionmsg\x12$\n" +
	"\rtransactionid\x18\x01 \x01(\x05R\rtransactionid\x12 \n" +
	"\vtokenstring\x18\x02 \x01(\tR\vtokenstring\"W\n" +
	"\x15getalltransactionsmsg\x12>\n" +
	"\blisttran\x18\x01 \x03(\v2\".accounttransaction.TransactionmsgR\blisttran2\x99\x04\n" +
	"\x12Transactionservice\x12]\n" +
	"\x0eAddtransaction\x12\".accounttransaction.Transactionmsg\x1a'.accounttransaction.transactionaddedmsg\x12g\n" +
	"\x11Updatetransaction\x12(.accounttransaction.Updatetransactionmsg\x1a(.accounttransaction.transactionstatusmsg\x12i\n" +
	"\x11Getalltransaction\x12).accounttransaction.getalltransactionsmsg\x1a).accounttransaction.getalltransactionsmsg\x12g\n" +
	"\x14Getsingletransaction\x12+.accounttransaction.getsingletransactionmsg\x1a\".accounttransaction.Transactionmsg\x12g\n" +
	"\x11deletetransaction\x12(.accounttransaction.Deletetransactionmsg\x1a(.accounttransaction.transactionstatusmsgB\x16Z\x14/transactionprotogenb\x06proto3"

var (
	file_transactions_proto_rawDescOnce sync.Once
	file_transactions_proto_rawDescData []byte
)

func file_transactions_proto_rawDescGZIP() []byte {
	file_transactions_proto_rawDescOnce.Do(func() {
		file_transactions_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_transactions_proto_rawDesc), len(file_transactions_proto_rawDesc)))
	})
	return file_transactions_proto_rawDescData
}

var file_transactions_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_transactions_proto_goTypes = []any{
	(*Transactionmsg)(nil),          // 0: accounttransaction.Transactionmsg
	(*Updatetransactionmsg)(nil),    // 1: accounttransaction.Updatetransactionmsg
	(*Deletetransactionmsg)(nil),    // 2: accounttransaction.Deletetransactionmsg
	(*Transactionaddedmsg)(nil),     // 3: accounttransaction.transactionaddedmsg
	(*Transactionstatusmsg)(nil),    // 4: accounttransaction.transactionstatusmsg
	(*Getsingletransactionmsg)(nil), // 5: accounttransaction.getsingletransactionmsg
	(*Getalltransactionsmsg)(nil),   // 6: accounttransaction.getalltransactionsmsg
}
var file_transactions_proto_depIdxs = []int32{
	0, // 0: accounttransaction.getalltransactionsmsg.listtran:type_name -> accounttransaction.Transactionmsg
	0, // 1: accounttransaction.Transactionservice.Addtransaction:input_type -> accounttransaction.Transactionmsg
	1, // 2: accounttransaction.Transactionservice.Updatetransaction:input_type -> accounttransaction.Updatetransactionmsg
	6, // 3: accounttransaction.Transactionservice.Getalltransaction:input_type -> accounttransaction.getalltransactionsmsg
	5, // 4: accounttransaction.Transactionservice.Getsingletransaction:input_type -> accounttransaction.getsingletransactionmsg
	2, // 5: accounttransaction.Transactionservice.deletetransaction:input_type -> accounttransaction.Deletetransactionmsg
	3, // 6: accounttransaction.Transactionservice.Addtransaction:output_type -> accounttransaction.transactionaddedmsg
	4, // 7: accounttransaction.Transactionservice.Updatetransaction:output_type -> accounttransaction.transactionstatusmsg
	6, // 8: accounttransaction.Transactionservice.Getalltransaction:output_type -> accounttransaction.getalltransactionsmsg
	0, // 9: accounttransaction.Transactionservice.Getsingletransaction:output_type -> accounttransaction.Transactionmsg
	4, // 10: accounttransaction.Transactionservice.deletetransaction:output_type -> accounttransaction.transactionstatusmsg
	6, // [6:11] is the sub-list for method output_type
	1, // [1:6] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_transactions_proto_init() }
func file_transactions_proto_init() {
	if File_transactions_proto != nil {
		return
	}
	file_transactions_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_transactions_proto_rawDesc), len(file_transactions_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_transactions_proto_goTypes,
		DependencyIndexes: file_transactions_proto_depIdxs,
		MessageInfos:      file_transactions_proto_msgTypes,
	}.Build()
	File_transactions_proto = out.File
	file_transactions_proto_goTypes = nil
	file_transactions_proto_depIdxs = nil
}
