// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v3.20.3
// source: account.proto

package protogen

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Accountmsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     int32                  `protobuf:"varint,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Balance       int32                  `protobuf:"varint,2,opt,name=balance,proto3" json:"balance,omitempty"`
	Owner         string                 `protobuf:"bytes,3,opt,name=owner,proto3" json:"owner,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Accountmsg) Reset() {
	*x = Accountmsg{}
	mi := &file_account_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Accountmsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Accountmsg) ProtoMessage() {}

func (x *Accountmsg) ProtoReflect() protoreflect.Message {
	mi := &file_account_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Accountmsg.ProtoReflect.Descriptor instead.
func (*Accountmsg) Descriptor() ([]byte, []int) {
	return file_account_proto_rawDescGZIP(), []int{0}
}

func (x *Accountmsg) GetAccountId() int32 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *Accountmsg) GetBalance() int32 {
	if x != nil {
		return x.Balance
	}
	return 0
}

func (x *Accountmsg) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *Accountmsg) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type Updateaccountmsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     int32                  `protobuf:"varint,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Tokenstring   string                 `protobuf:"bytes,5,opt,name=tokenstring,proto3" json:"tokenstring,omitempty"`
	Balance       *int32                 `protobuf:"varint,2,opt,name=balance,proto3,oneof" json:"balance,omitempty"`
	Owner         *string                `protobuf:"bytes,3,opt,name=owner,proto3,oneof" json:"owner,omitempty"`
	Status        *string                `protobuf:"bytes,4,opt,name=status,proto3,oneof" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Updateaccountmsg) Reset() {
	*x = Updateaccountmsg{}
	mi := &file_account_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Updateaccountmsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Updateaccountmsg) ProtoMessage() {}

func (x *Updateaccountmsg) ProtoReflect() protoreflect.Message {
	mi := &file_account_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Updateaccountmsg.ProtoReflect.Descriptor instead.
func (*Updateaccountmsg) Descriptor() ([]byte, []int) {
	return file_account_proto_rawDescGZIP(), []int{1}
}

func (x *Updateaccountmsg) GetAccountId() int32 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *Updateaccountmsg) GetTokenstring() string {
	if x != nil {
		return x.Tokenstring
	}
	return ""
}

func (x *Updateaccountmsg) GetBalance() int32 {
	if x != nil && x.Balance != nil {
		return *x.Balance
	}
	return 0
}

func (x *Updateaccountmsg) GetOwner() string {
	if x != nil && x.Owner != nil {
		return *x.Owner
	}
	return ""
}

func (x *Updateaccountmsg) GetStatus() string {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return ""
}

type Deleteaccountmsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     int32                  `protobuf:"varint,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Tokenstring   string                 `protobuf:"bytes,2,opt,name=tokenstring,proto3" json:"tokenstring,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Deleteaccountmsg) Reset() {
	*x = Deleteaccountmsg{}
	mi := &file_account_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Deleteaccountmsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Deleteaccountmsg) ProtoMessage() {}

func (x *Deleteaccountmsg) ProtoReflect() protoreflect.Message {
	mi := &file_account_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Deleteaccountmsg.ProtoReflect.Descriptor instead.
func (*Deleteaccountmsg) Descriptor() ([]byte, []int) {
	return file_account_proto_rawDescGZIP(), []int{2}
}

func (x *Deleteaccountmsg) GetAccountId() int32 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *Deleteaccountmsg) GetTokenstring() string {
	if x != nil {
		return x.Tokenstring
	}
	return ""
}

type Accountaddedmsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tokenstring   string                 `protobuf:"bytes,1,opt,name=tokenstring,proto3" json:"tokenstring,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Accountaddedmsg) Reset() {
	*x = Accountaddedmsg{}
	mi := &file_account_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Accountaddedmsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Accountaddedmsg) ProtoMessage() {}

func (x *Accountaddedmsg) ProtoReflect() protoreflect.Message {
	mi := &file_account_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Accountaddedmsg.ProtoReflect.Descriptor instead.
func (*Accountaddedmsg) Descriptor() ([]byte, []int) {
	return file_account_proto_rawDescGZIP(), []int{3}
}

func (x *Accountaddedmsg) GetTokenstring() string {
	if x != nil {
		return x.Tokenstring
	}
	return ""
}

func (x *Accountaddedmsg) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type Statusmsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Status        int32                  `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Statusmsg) Reset() {
	*x = Statusmsg{}
	mi := &file_account_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Statusmsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Statusmsg) ProtoMessage() {}

func (x *Statusmsg) ProtoReflect() protoreflect.Message {
	mi := &file_account_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Statusmsg.ProtoReflect.Descriptor instead.
func (*Statusmsg) Descriptor() ([]byte, []int) {
	return file_account_proto_rawDescGZIP(), []int{4}
}

func (x *Statusmsg) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Statusmsg) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type Getsingleaccmsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     int32                  `protobuf:"varint,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Tokenstring   string                 `protobuf:"bytes,2,opt,name=tokenstring,proto3" json:"tokenstring,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Getsingleaccmsg) Reset() {
	*x = Getsingleaccmsg{}
	mi := &file_account_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Getsingleaccmsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Getsingleaccmsg) ProtoMessage() {}

func (x *Getsingleaccmsg) ProtoReflect() protoreflect.Message {
	mi := &file_account_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Getsingleaccmsg.ProtoReflect.Descriptor instead.
func (*Getsingleaccmsg) Descriptor() ([]byte, []int) {
	return file_account_proto_rawDescGZIP(), []int{5}
}

func (x *Getsingleaccmsg) GetAccountId() int32 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *Getsingleaccmsg) GetTokenstring() string {
	if x != nil {
		return x.Tokenstring
	}
	return ""
}

type Getallaccountsmsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Listaccs      []*Accountmsg          `protobuf:"bytes,1,rep,name=listaccs,proto3" json:"listaccs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Getallaccountsmsg) Reset() {
	*x = Getallaccountsmsg{}
	mi := &file_account_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Getallaccountsmsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Getallaccountsmsg) ProtoMessage() {}

func (x *Getallaccountsmsg) ProtoReflect() protoreflect.Message {
	mi := &file_account_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Getallaccountsmsg.ProtoReflect.Descriptor instead.
func (*Getallaccountsmsg) Descriptor() ([]byte, []int) {
	return file_account_proto_rawDescGZIP(), []int{6}
}

func (x *Getallaccountsmsg) GetListaccs() []*Accountmsg {
	if x != nil {
		return x.Listaccs
	}
	return nil
}

var File_account_proto protoreflect.FileDescriptor

const file_account_proto_rawDesc = "" +
	"\n" +
	"\raccount.proto\x12\x12accounttransaction\"s\n" +
	"\n" +
	"Accountmsg\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\x05R\taccountId\x12\x18\n" +
	"\abalance\x18\x02 \x01(\x05R\abalance\x12\x14\n" +
	"\x05owner\x18\x03 \x01(\tR\x05owner\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\"\xcb\x01\n" +
	"\x10Updateaccountmsg\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\x05R\taccountId\x12 \n" +
	"\vtokenstring\x18\x05 \x01(\tR\vtokenstring\x12\x1d\n" +
	"\abalance\x18\x02 \x01(\x05H\x00R\abalance\x88\x01\x01\x12\x19\n" +
	"\x05owner\x18\x03 \x01(\tH\x01R\x05owner\x88\x01\x01\x12\x1b\n" +
	"\x06status\x18\x04 \x01(\tH\x02R\x06status\x88\x01\x01B\n" +
	"\n" +
	"\b_balanceB\b\n" +
	"\x06_ownerB\t\n" +
	"\a_status\"S\n" +
	"\x10Deleteaccountmsg\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\x05R\taccountId\x12 \n" +
	"\vtokenstring\x18\x02 \x01(\tR\vtokenstring\"M\n" +
	"\x0faccountaddedmsg\x12 \n" +
	"\vtokenstring\x18\x01 \x01(\tR\vtokenstring\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"=\n" +
	"\tstatusmsg\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x16\n" +
	"\x06status\x18\x02 \x01(\x05R\x06status\"R\n" +
	"\x0fgetsingleaccmsg\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\x05R\taccountId\x12 \n" +
	"\vtokenstring\x18\x02 \x01(\tR\vtokenstring\"O\n" +
	"\x11getallaccountsmsg\x12:\n" +
	"\blistaccs\x18\x01 \x03(\v2\x1e.accounttransaction.AccountmsgR\blistaccs2\xc9\x03\n" +
	"\x0eAccountservice\x12Q\n" +
	"\n" +
	"Addaccount\x12\x1e.accounttransaction.Accountmsg\x1a#.accounttransaction.accountaddedmsg\x12T\n" +
	"\rUpdateaccount\x12$.accounttransaction.Updateaccountmsg\x1a\x1d.accounttransaction.statusmsg\x12^\n" +
	"\x0eGetallaccounts\x12%.accounttransaction.getallaccountsmsg\x1a%.accounttransaction.getallaccountsmsg\x12X\n" +
	"\x11Getsingleaccounts\x12#.accounttransaction.getsingleaccmsg\x1a\x1e.accounttransaction.Accountmsg\x12T\n" +
	"\rdeleteaccount\x12$.accounttransaction.Deleteaccountmsg\x1a\x1d.accounttransaction.statusmsgB\vZ\t/protogenb\x06proto3"

var (
	file_account_proto_rawDescOnce sync.Once
	file_account_proto_rawDescData []byte
)

func file_account_proto_rawDescGZIP() []byte {
	file_account_proto_rawDescOnce.Do(func() {
		file_account_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_account_proto_rawDesc), len(file_account_proto_rawDesc)))
	})
	return file_account_proto_rawDescData
}

var file_account_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_account_proto_goTypes = []any{
	(*Accountmsg)(nil),        // 0: accounttransaction.Accountmsg
	(*Updateaccountmsg)(nil),  // 1: accounttransaction.Updateaccountmsg
	(*Deleteaccountmsg)(nil),  // 2: accounttransaction.Deleteaccountmsg
	(*Accountaddedmsg)(nil),   // 3: accounttransaction.accountaddedmsg
	(*Statusmsg)(nil),         // 4: accounttransaction.statusmsg
	(*Getsingleaccmsg)(nil),   // 5: accounttransaction.getsingleaccmsg
	(*Getallaccountsmsg)(nil), // 6: accounttransaction.getallaccountsmsg
}
var file_account_proto_depIdxs = []int32{
	0, // 0: accounttransaction.getallaccountsmsg.listaccs:type_name -> accounttransaction.Accountmsg
	0, // 1: accounttransaction.Accountservice.Addaccount:input_type -> accounttransaction.Accountmsg
	1, // 2: accounttransaction.Accountservice.Updateaccount:input_type -> accounttransaction.Updateaccountmsg
	6, // 3: accounttransaction.Accountservice.Getallaccounts:input_type -> accounttransaction.getallaccountsmsg
	5, // 4: accounttransaction.Accountservice.Getsingleaccounts:input_type -> accounttransaction.getsingleaccmsg
	2, // 5: accounttransaction.Accountservice.deleteaccount:input_type -> accounttransaction.Deleteaccountmsg
	3, // 6: accounttransaction.Accountservice.Addaccount:output_type -> accounttransaction.accountaddedmsg
	4, // 7: accounttransaction.Accountservice.Updateaccount:output_type -> accounttransaction.statusmsg
	6, // 8: accounttransaction.Accountservice.Getallaccounts:output_type -> accounttransaction.getallaccountsmsg
	0, // 9: accounttransaction.Accountservice.Getsingleaccounts:output_type -> accounttransaction.Accountmsg
	4, // 10: accounttransaction.Accountservice.deleteaccount:output_type -> accounttransaction.statusmsg
	6, // [6:11] is the sub-list for method output_type
	1, // [1:6] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_account_proto_init() }
func file_account_proto_init() {
	if File_account_proto != nil {
		return
	}
	file_account_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_account_proto_rawDesc), len(file_account_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_account_proto_goTypes,
		DependencyIndexes: file_account_proto_depIdxs,
		MessageInfos:      file_account_proto_msgTypes,
	}.Build()
	File_account_proto = out.File
	file_account_proto_goTypes = nil
	file_account_proto_depIdxs = nil
}
